### ISSUE TITLE
Sample f-simple program

### ISSUE THREAD

**Issue by DanProgrammer1999** [DanProgrammer1999/f-simple#3]
### Create a sample program in our language 

This is important so that we could test various parts of the interpreter. 

The program needs to cover as much of the language's lexical, syntax and semantic rules, as possible.
Try to see where our implementation could fail and make some expressions for those cases.

**Comment by BoogiemanNSK** [comment]
**Demo 1**
Wrote a program that includes recursion, loops and lists concatenation (it searches for first n Fibonacci numbers). However, it is mostly useless, until we have some print function or some ways to see what is in memory.

**Comment by BoogiemanNSK** [comment]
**Demo 2**
Another simple program, that is calculating quadratic equation, with arguments hardcoded.

Probably I will one more demo later and that'll be enough.

**Comment by BoogiemanNSK** [comment]
**Demo3**
This one just sums up the rest functionality, so probably these 3 programs are enough.
The only thing left to do is Print() funciton, so that we could test our programs, but that is other story...
